backup/baseConhecimento/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using baseConhecimento.Models;
using System.Data.SqlClient;
using MySql.Data.MySqlClient;
//using System.Data.SqlServerCe;

namespace baseConhecimento.Controllers
{
    public class ItemsController : Controller
    {
        //private Context db = new Context();
        Context db = new Context();
        // GET: Items
        public ActionResult Index()
        {
            Context db = new Context();
            //dados = db.conecta().;
            //MySqlConnection conn = db.conecta();
            //MySqlCommand cmd = new MySqlCommand("select *from ic",conn);
            //MySqlDataReader reader = cmd.ExecuteReader();
            return View(db.retornadados_item());
        }
        // GET: Items/Details/5
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.retornavalor(id);
            db.somaranking(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_ic,nome,descricao,imagem")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.inseredados(item);
                return RedirectToAction("Index");
            }

            return View(item);
        }
        // GET: Items/Edit/5
        public ActionResult Edit(int id)
        {
            if (id < 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.retornavalor(id);
            if (item.nome == "")
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_ic,nome,descricao,ranking,imagem")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.alteradados(item);
                return RedirectToAction("Index");
            }
            return View(item);
        }
        // GET: Items/Delete/5
        public ActionResult Delete(int id)
        {
            if (id < 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            db.deletadados(id);
            return RedirectToAction("Index");
        }

        /*// POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.deletadados(id);
            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }*/
    }
}

backup/baseConhecimento/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-head er" id="menufirst">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Base de Conhecimento - CVC", "Index", "Items", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" id="menusecond">
                    <li>@Html.ActionLink("Itens de Configuração", "Index", "Items")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <!--p>&copy; @DateTime.Now.Year - My ASP.NET Application</p-->
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>